<?php

namespace Database\Seeders;

use App\Models\City;
use Illuminate\Database\Seeder;

class CitySeeder extends Seeder
{
    public function run()
    {
        City::create(['id' => 1101, 'province_id' => 11, 'nama' => 'KAB. ACEH SELATAN']);
        City::create(['id' => 1102, 'province_id' => 11, 'nama' => 'KAB. ACEH TENGGARA']);
        City::create(['id' => 1103, 'province_id' => 11, 'nama' => 'KAB. ACEH TIMUR']);
        City::create(['id' => 1104, 'province_id' => 11, 'nama' => 'KAB. ACEH TENGAH']);
        City::create(['id' => 1105, 'province_id' => 11, 'nama' => 'KAB. ACEH BARAT']);
        City::create(['id' => 1106, 'province_id' => 11, 'nama' => 'KAB. ACEH BESAR']);
        City::create(['id' => 1107, 'province_id' => 11, 'nama' => 'KAB. PIDIE']);
        City::create(['id' => 1108, 'province_id' => 11, 'nama' => 'KAB. ACEH UTARA']);
        City::create(['id' => 1109, 'province_id' => 11, 'nama' => 'KAB. SIMEULUE']);
        City::create(['id' => 1110, 'province_id' => 11, 'nama' => 'KAB. ACEH SINGKIL']);
        City::create(['id' => 1111, 'province_id' => 11, 'nama' => 'KAB. BIREUEN']);
        City::create(['id' => 1112, 'province_id' => 11, 'nama' => 'KAB. ACEH BARAT DAYA']);
        City::create(['id' => 1113, 'province_id' => 11, 'nama' => 'KAB. GAYO LUES']);
        City::create(['id' => 1114, 'province_id' => 11, 'nama' => 'KAB. ACEH JAYA']);
        City::create(['id' => 1115, 'province_id' => 11, 'nama' => 'KAB. NAGAN RAYA']);
        City::create(['id' => 1116, 'province_id' => 11, 'nama' => 'KAB. ACEH TAMIANG']);
        City::create(['id' => 1117, 'province_id' => 11, 'nama' => 'KAB. BENER MERIAH']);
        City::create(['id' => 1118, 'province_id' => 11, 'nama' => 'KAB. PIDIE JAYA']);
        City::create(['id' => 1171, 'province_id' => 11, 'nama' => 'KOTA BANDA ACEH']);
        City::create(['id' => 1172, 'province_id' => 11, 'nama' => 'KOTA SABANG']);
        City::create(['id' => 1173, 'province_id' => 11, 'nama' => 'KOTA LHOKSEUMAWE']);
        City::create(['id' => 1174, 'province_id' => 11, 'nama' => 'KOTA LANGSA']);
        City::create(['id' => 1175, 'province_id' => 11, 'nama' => 'KOTA SUBULUSSALAM']);
        City::create(['id' => 1201, 'province_id' => 12, 'nama' => 'KAB. TAPANULI TENGAH']);
        City::create(['id' => 1202, 'province_id' => 12, 'nama' => 'KAB. TAPANULI UTARA']);
        City::create(['id' => 1203, 'province_id' => 12, 'nama' => 'KAB. TAPANULI SELATAN']);
        City::create(['id' => 1204, 'province_id' => 12, 'nama' => 'KAB. NIAS']);
        City::create(['id' => 1205, 'province_id' => 12, 'nama' => 'KAB. LANGKAT']);
        City::create(['id' => 1206, 'province_id' => 12, 'nama' => 'KAB. KARO']);
        City::create(['id' => 1207, 'province_id' => 12, 'nama' => 'KAB. DELI SERDANG']);
        City::create(['id' => 1208, 'province_id' => 12, 'nama' => 'KAB. SIMALUNGUN']);
        City::create(['id' => 1209, 'province_id' => 12, 'nama' => 'KAB. ASAHAN']);
        City::create(['id' => 1210, 'province_id' => 12, 'nama' => 'KAB. LABUHANBATU']);
        City::create(['id' => 1211, 'province_id' => 12, 'nama' => 'KAB. DAIRI']);
        City::create(['id' => 1212, 'province_id' => 12, 'nama' => 'KAB. TOBA SAMOSIR']);
        City::create(['id' => 1213, 'province_id' => 12, 'nama' => 'KAB. MANDAILING NATAL']);
        City::create(['id' => 1214, 'province_id' => 12, 'nama' => 'KAB. NIAS SELATAN']);
        City::create(['id' => 1215, 'province_id' => 12, 'nama' => 'KAB. PAKPAK BHARAT']);
        City::create(['id' => 1216, 'province_id' => 12, 'nama' => 'KAB. HUMBANG HASUNDUTAN']);
        City::create(['id' => 1217, 'province_id' => 12, 'nama' => 'KAB. SAMOSIR']);
        City::create(['id' => 1218, 'province_id' => 12, 'nama' => 'KAB. SERDANG BEDAGAI']);
        City::create(['id' => 1219, 'province_id' => 12, 'nama' => 'KAB. BATU BARA']);
        City::create(['id' => 1220, 'province_id' => 12, 'nama' => 'KAB. PADANG LAWAS UTARA']);
        City::create(['id' => 1221, 'province_id' => 12, 'nama' => 'KAB. PADANG LAWAS']);
        City::create(['id' => 1222, 'province_id' => 12, 'nama' => 'KAB. LABUHANBATU SELATAN']);
        City::create(['id' => 1223, 'province_id' => 12, 'nama' => 'KAB. LABUHANBATU UTARA']);
        City::create(['id' => 1224, 'province_id' => 12, 'nama' => 'KAB. NIAS UTARA']);
        City::create(['id' => 1225, 'province_id' => 12, 'nama' => 'KAB. NIAS BARAT']);
        City::create(['id' => 1271, 'province_id' => 12, 'nama' => 'KOTA MEDAN']);
        City::create(['id' => 1272, 'province_id' => 12, 'nama' => 'KOTA PEMATANGSIANTAR']);
        City::create(['id' => 1273, 'province_id' => 12, 'nama' => 'KOTA SIBOLGA']);
        City::create(['id' => 1274, 'province_id' => 12, 'nama' => 'KOTA TANJUNG BALAI']);
        City::create(['id' => 1275, 'province_id' => 12, 'nama' => 'KOTA BINJAI']);
        City::create(['id' => 1276, 'province_id' => 12, 'nama' => 'KOTA TEBING TINGGI']);
        City::create(['id' => 1277, 'province_id' => 12, 'nama' => 'KOTA PADANGSIDIMPUAN']);
        City::create(['id' => 1278, 'province_id' => 12, 'nama' => 'KOTA GUNUNGSITOLI']);
        City::create(['id' => 1301, 'province_id' => 13, 'nama' => 'KAB. PESISIR SELATAN']);
        City::create(['id' => 1302, 'province_id' => 13, 'nama' => 'KAB. SOLOK']);
        City::create(['id' => 1303, 'province_id' => 13, 'nama' => 'KAB. SIJUNJUNG']);
        City::create(['id' => 1304, 'province_id' => 13, 'nama' => 'KAB. TANAH DATAR']);
        City::create(['id' => 1305, 'province_id' => 13, 'nama' => 'KAB. PADANG PARIAMAN']);
        City::create(['id' => 1306, 'province_id' => 13, 'nama' => 'KAB. AGAM']);
        City::create(['id' => 1307, 'province_id' => 13, 'nama' => 'KAB. LIMA PULUH KOTA']);
        City::create(['id' => 1308, 'province_id' => 13, 'nama' => 'KAB. PASAMAN']);
        City::create(['id' => 1309, 'province_id' => 13, 'nama' => 'KAB. KEPULAUAN MENTAWAI']);
        City::create(['id' => 1310, 'province_id' => 13, 'nama' => 'KAB. DHARMASRAYA']);
        City::create(['id' => 1311, 'province_id' => 13, 'nama' => 'KAB. SOLOK SELATAN']);
        City::create(['id' => 1312, 'province_id' => 13, 'nama' => 'KAB. PASAMAN BARAT']);
        City::create(['id' => 1371, 'province_id' => 13, 'nama' => 'KOTA PADANG']);
        City::create(['id' => 1372, 'province_id' => 13, 'nama' => 'KOTA SOLOK']);
        City::create(['id' => 1373, 'province_id' => 13, 'nama' => 'KOTA SAWAHLUNTO']);
        City::create(['id' => 1374, 'province_id' => 13, 'nama' => 'KOTA PADANG PANJANG']);
        City::create(['id' => 1375, 'province_id' => 13, 'nama' => 'KOTA BUKITTINGGI']);
        City::create(['id' => 1376, 'province_id' => 13, 'nama' => 'KOTA PAYAKUMBUH']);
        City::create(['id' => 1377, 'province_id' => 13, 'nama' => 'KOTA PARIAMAN']);
        City::create(['id' => 1401, 'province_id' => 14, 'nama' => 'KAB. KAMPAR']);
        City::create(['id' => 1402, 'province_id' => 14, 'nama' => 'KAB. INDRAGIRI HULU']);
        City::create(['id' => 1403, 'province_id' => 14, 'nama' => 'KAB. BENGKALIS']);
        City::create(['id' => 1404, 'province_id' => 14, 'nama' => 'KAB. INDRAGIRI HILIR']);
        City::create(['id' => 1405, 'province_id' => 14, 'nama' => 'KAB. PELALAWAN']);
        City::create(['id' => 1406, 'province_id' => 14, 'nama' => 'KAB. ROKAN HULU']);
        City::create(['id' => 1407, 'province_id' => 14, 'nama' => 'KAB. ROKAN HILIR']);
        City::create(['id' => 1408, 'province_id' => 14, 'nama' => 'KAB. SIAK']);
        City::create(['id' => 1409, 'province_id' => 14, 'nama' => 'KAB. KUANTAN SINGINGI']);
        City::create(['id' => 1410, 'province_id' => 14, 'nama' => 'KAB. KEPULAUAN MERANTI']);
        City::create(['id' => 1471, 'province_id' => 14, 'nama' => 'KOTA PEKANBARU']);
        City::create(['id' => 1472, 'province_id' => 14, 'nama' => 'KOTA DUMAI']);
        City::create(['id' => 1501, 'province_id' => 15, 'nama' => 'KAB. KERINCI']);
        City::create(['id' => 1502, 'province_id' => 15, 'nama' => 'KAB. MERANGIN']);
        City::create(['id' => 1503, 'province_id' => 15, 'nama' => 'KAB. SAROLANGUN']);
        City::create(['id' => 1504, 'province_id' => 15, 'nama' => 'KAB. BATANGHARI']);
        City::create(['id' => 1505, 'province_id' => 15, 'nama' => 'KAB. MUARO JAMBI']);
        City::create(['id' => 1506, 'province_id' => 15, 'nama' => 'KAB. TANJUNG JABUNG BARAT']);
        City::create(['id' => 1507, 'province_id' => 15, 'nama' => 'KAB. TANJUNG JABUNG TIMUR']);
        City::create(['id' => 1508, 'province_id' => 15, 'nama' => 'KAB. BUNGO']);
        City::create(['id' => 1509, 'province_id' => 15, 'nama' => 'KAB. TEBO']);
        City::create(['id' => 1571, 'province_id' => 15, 'nama' => 'KOTA JAMBI']);
        City::create(['id' => 1572, 'province_id' => 15, 'nama' => 'KOTA SUNGAI PENUH']);
        City::create(['id' => 1601, 'province_id' => 16, 'nama' => 'KAB. OGAN KOMERING ULU']);
        City::create(['id' => 1602, 'province_id' => 16, 'nama' => 'KAB. OGAN KOMERING ILIR']);
        City::create(['id' => 1603, 'province_id' => 16, 'nama' => 'KAB. MUARA ENIM']);
        City::create(['id' => 1604, 'province_id' => 16, 'nama' => 'KAB. LAHAT']);
        City::create(['id' => 1605, 'province_id' => 16, 'nama' => 'KAB. MUSI RAWAS']);
        City::create(['id' => 1606, 'province_id' => 16, 'nama' => 'KAB. MUSI BANYUASIN']);
        City::create(['id' => 1607, 'province_id' => 16, 'nama' => 'KAB. BANYUASIN']);
        City::create(['id' => 1608, 'province_id' => 16, 'nama' => 'KAB. OGAN KOMERING ULU TIMUR']);
        City::create(['id' => 1609, 'province_id' => 16, 'nama' => 'KAB. OGAN KOMERING ULU SELATAN']);
        City::create(['id' => 1610, 'province_id' => 16, 'nama' => 'KAB. OGAN ILIR']);
        City::create(['id' => 1611, 'province_id' => 16, 'nama' => 'KAB. EMPAT LAWANG']);
        City::create(['id' => 1612, 'province_id' => 16, 'nama' => 'KAB. PENUKAL ABAB LEMATANG ILIR']);
        City::create(['id' => 1613, 'province_id' => 16, 'nama' => 'KAB. MUSI RAWAS UTARA']);
        City::create(['id' => 1671, 'province_id' => 16, 'nama' => 'KOTA PALEMBANG']);
        City::create(['id' => 1672, 'province_id' => 16, 'nama' => 'KOTA PAGAR ALAM']);
        City::create(['id' => 1673, 'province_id' => 16, 'nama' => 'KOTA LUBUK LINGGAU']);
        City::create(['id' => 1674, 'province_id' => 16, 'nama' => 'KOTA PRABUMULIH']);
        City::create(['id' => 1701, 'province_id' => 17, 'nama' => 'KAB. BENGKULU SELATAN']);
        City::create(['id' => 1702, 'province_id' => 17, 'nama' => 'KAB. REJANG LEBONG']);
        City::create(['id' => 1703, 'province_id' => 17, 'nama' => 'KAB. BENGKULU UTARA']);
        City::create(['id' => 1704, 'province_id' => 17, 'nama' => 'KAB. KAUR']);
        City::create(['id' => 1705, 'province_id' => 17, 'nama' => 'KAB. SELUMA']);
        City::create(['id' => 1706, 'province_id' => 17, 'nama' => 'KAB. MUKO MUKO']);
        City::create(['id' => 1707, 'province_id' => 17, 'nama' => 'KAB. LEBONG']);
        City::create(['id' => 1708, 'province_id' => 17, 'nama' => 'KAB. KEPAHIANG']);
        City::create(['id' => 1709, 'province_id' => 17, 'nama' => 'KAB. BENGKULU TENGAH']);
        City::create(['id' => 1771, 'province_id' => 17, 'nama' => 'KOTA BENGKULU']);
        City::create(['id' => 1801, 'province_id' => 18, 'nama' => 'KAB. LAMPUNG SELATAN']);
        City::create(['id' => 1802, 'province_id' => 18, 'nama' => 'KAB. LAMPUNG TENGAH']);
        City::create(['id' => 1803, 'province_id' => 18, 'nama' => 'KAB. LAMPUNG UTARA']);
        City::create(['id' => 1804, 'province_id' => 18, 'nama' => 'KAB. LAMPUNG BARAT']);
        City::create(['id' => 1805, 'province_id' => 18, 'nama' => 'KAB. TULANG BAWANG']);
        City::create(['id' => 1806, 'province_id' => 18, 'nama' => 'KAB. TANGGAMUS']);
        City::create(['id' => 1807, 'province_id' => 18, 'nama' => 'KAB. LAMPUNG TIMUR']);
        City::create(['id' => 1808, 'province_id' => 18, 'nama' => 'KAB. WAY KANAN']);
        City::create(['id' => 1809, 'province_id' => 18, 'nama' => 'KAB. PESAWARAN']);
        City::create(['id' => 1810, 'province_id' => 18, 'nama' => 'KAB. PRINGSEWU']);
        City::create(['id' => 1811, 'province_id' => 18, 'nama' => 'KAB. MESUJI']);
        City::create(['id' => 1812, 'province_id' => 18, 'nama' => 'KAB. TULANG BAWANG BARAT']);
        City::create(['id' => 1813, 'province_id' => 18, 'nama' => 'KAB. PESISIR BARAT']);
        City::create(['id' => 1871, 'province_id' => 18, 'nama' => 'KOTA BANDAR LAMPUNG']);
        City::create(['id' => 1872, 'province_id' => 18, 'nama' => 'KOTA METRO']);
        City::create(['id' => 1901, 'province_id' => 19, 'nama' => 'KAB. BANGKA']);
        City::create(['id' => 1902, 'province_id' => 19, 'nama' => 'KAB. BELITUNG']);
        City::create(['id' => 1903, 'province_id' => 19, 'nama' => 'KAB. BANGKA SELATAN']);
        City::create(['id' => 1904, 'province_id' => 19, 'nama' => 'KAB. BANGKA TENGAH']);
        City::create(['id' => 1905, 'province_id' => 19, 'nama' => 'KAB. BANGKA BARAT']);
        City::create(['id' => 1906, 'province_id' => 19, 'nama' => 'KAB. BELITUNG TIMUR']);
        City::create(['id' => 1971, 'province_id' => 19, 'nama' => 'KOTA PANGKAL PINANG']);
        City::create(['id' => 2101, 'province_id' => 21, 'nama' => 'KAB. BINTAN']);
        City::create(['id' => 2102, 'province_id' => 21, 'nama' => 'KAB. KARIMUN']);
        City::create(['id' => 2103, 'province_id' => 21, 'nama' => 'KAB. NATUNA']);
        City::create(['id' => 2104, 'province_id' => 21, 'nama' => 'KAB. LINGGA']);
        City::create(['id' => 2105, 'province_id' => 21, 'nama' => 'KAB. KEPULAUAN ANAMBAS']);
        City::create(['id' => 2171, 'province_id' => 21, 'nama' => 'KOTA BATAM']);
        City::create(['id' => 2172, 'province_id' => 21, 'nama' => 'KOTA TANJUNG PINANG']);
        City::create(['id' => 3101, 'province_id' => 31, 'nama' => 'KAB. ADM. KEP. SERIBU']);
        City::create(['id' => 3171, 'province_id' => 31, 'nama' => 'KOTA ADM. JAKARTA PUSAT']);
        City::create(['id' => 3172, 'province_id' => 31, 'nama' => 'KOTA ADM. JAKARTA UTARA']);
        City::create(['id' => 3173, 'province_id' => 31, 'nama' => 'KOTA ADM. JAKARTA BARAT']);
        City::create(['id' => 3174, 'province_id' => 31, 'nama' => 'KOTA ADM. JAKARTA SELATAN']);
        City::create(['id' => 3175, 'province_id' => 31, 'nama' => 'KOTA ADM. JAKARTA TIMUR']);
        City::create(['id' => 3201, 'province_id' => 32, 'nama' => 'KAB. BOGOR']);
        City::create(['id' => 3202, 'province_id' => 32, 'nama' => 'KAB. SUKABUMI']);
        City::create(['id' => 3203, 'province_id' => 32, 'nama' => 'KAB. CIANJUR']);
        City::create(['id' => 3204, 'province_id' => 32, 'nama' => 'KAB. BANDUNG']);
        City::create(['id' => 3205, 'province_id' => 32, 'nama' => 'KAB. GARUT']);
        City::create(['id' => 3206, 'province_id' => 32, 'nama' => 'KAB. TASIKMALAYA']);
        City::create(['id' => 3207, 'province_id' => 32, 'nama' => 'KAB. CIAMIS']);
        City::create(['id' => 3208, 'province_id' => 32, 'nama' => 'KAB. KUNINGAN']);
        City::create(['id' => 3209, 'province_id' => 32, 'nama' => 'KAB. CIREBON']);
        City::create(['id' => 3210, 'province_id' => 32, 'nama' => 'KAB. MAJALENGKA']);
        City::create(['id' => 3211, 'province_id' => 32, 'nama' => 'KAB. SUMEDANG']);
        City::create(['id' => 3212, 'province_id' => 32, 'nama' => 'KAB. INDRAMAYU']);
        City::create(['id' => 3213, 'province_id' => 32, 'nama' => 'KAB. SUBANG']);
        City::create(['id' => 3214, 'province_id' => 32, 'nama' => 'KAB. PURWAKARTA']);
        City::create(['id' => 3215, 'province_id' => 32, 'nama' => 'KAB. KARAWANG']);
        City::create(['id' => 3216, 'province_id' => 32, 'nama' => 'KAB. BEKASI']);
        City::create(['id' => 3217, 'province_id' => 32, 'nama' => 'KAB. BANDUNG BARAT']);
        City::create(['id' => 3218, 'province_id' => 32, 'nama' => 'KAB. PANGANDARAN']);
        City::create(['id' => 3271, 'province_id' => 32, 'nama' => 'KOTA BOGOR']);
        City::create(['id' => 3272, 'province_id' => 32, 'nama' => 'KOTA SUKABUMI']);
        City::create(['id' => 3273, 'province_id' => 32, 'nama' => 'KOTA BANDUNG']);
        City::create(['id' => 3274, 'province_id' => 32, 'nama' => 'KOTA CIREBON']);
        City::create(['id' => 3275, 'province_id' => 32, 'nama' => 'KOTA BEKASI']);
        City::create(['id' => 3276, 'province_id' => 32, 'nama' => 'KOTA DEPOK']);
        City::create(['id' => 3277, 'province_id' => 32, 'nama' => 'KOTA CIMAHI']);
        City::create(['id' => 3278, 'province_id' => 32, 'nama' => 'KOTA TASIKMALAYA']);
        City::create(['id' => 3279, 'province_id' => 32, 'nama' => 'KOTA BANJAR']);
        City::create(['id' => 3301, 'province_id' => 33, 'nama' => 'KAB. CILACAP']);
        City::create(['id' => 3302, 'province_id' => 33, 'nama' => 'KAB. BANYUMAS']);
        City::create(['id' => 3303, 'province_id' => 33, 'nama' => 'KAB. PURBALINGGA']);
        City::create(['id' => 3304, 'province_id' => 33, 'nama' => 'KAB. BANJARNEGARA']);
        City::create(['id' => 3305, 'province_id' => 33, 'nama' => 'KAB. KEBUMEN']);
        City::create(['id' => 3306, 'province_id' => 33, 'nama' => 'KAB. PURWOREJO']);
        City::create(['id' => 3307, 'province_id' => 33, 'nama' => 'KAB. WONOSOBO']);
        City::create(['id' => 3308, 'province_id' => 33, 'nama' => 'KAB. MAGELANG']);
        City::create(['id' => 3309, 'province_id' => 33, 'nama' => 'KAB. BOYOLALI']);
        City::create(['id' => 3310, 'province_id' => 33, 'nama' => 'KAB. KLATEN']);
        City::create(['id' => 3311, 'province_id' => 33, 'nama' => 'KAB. SUKOHARJO']);
        City::create(['id' => 3312, 'province_id' => 33, 'nama' => 'KAB. WONOGIRI']);
        City::create(['id' => 3313, 'province_id' => 33, 'nama' => 'KAB. KARANGANYAR']);
        City::create(['id' => 3314, 'province_id' => 33, 'nama' => 'KAB. SRAGEN']);
        City::create(['id' => 3315, 'province_id' => 33, 'nama' => 'KAB. GROBOGAN']);
        City::create(['id' => 3316, 'province_id' => 33, 'nama' => 'KAB. BLORA']);
        City::create(['id' => 3317, 'province_id' => 33, 'nama' => 'KAB. REMBANG']);
        City::create(['id' => 3318, 'province_id' => 33, 'nama' => 'KAB. PATI']);
        City::create(['id' => 3319, 'province_id' => 33, 'nama' => 'KAB. KUDUS']);
        City::create(['id' => 3320, 'province_id' => 33, 'nama' => 'KAB. JEPARA']);
        City::create(['id' => 3321, 'province_id' => 33, 'nama' => 'KAB. DEMAK']);
        City::create(['id' => 3322, 'province_id' => 33, 'nama' => 'KAB. SEMARANG']);
        City::create(['id' => 3323, 'province_id' => 33, 'nama' => 'KAB. TEMANGGUNG']);
        City::create(['id' => 3324, 'province_id' => 33, 'nama' => 'KAB. KENDAL']);
        City::create(['id' => 3325, 'province_id' => 33, 'nama' => 'KAB. BATANG']);
        City::create(['id' => 3326, 'province_id' => 33, 'nama' => 'KAB. PEKALONGAN']);
        City::create(['id' => 3327, 'province_id' => 33, 'nama' => 'KAB. PEMALANG']);
        City::create(['id' => 3328, 'province_id' => 33, 'nama' => 'KAB. TEGAL']);
        City::create(['id' => 3329, 'province_id' => 33, 'nama' => 'KAB. BREBES']);
        City::create(['id' => 3371, 'province_id' => 33, 'nama' => 'KOTA MAGELANG']);
        City::create(['id' => 3372, 'province_id' => 33, 'nama' => 'KOTA SURAKARTA']);
        City::create(['id' => 3373, 'province_id' => 33, 'nama' => 'KOTA SALATIGA']);
        City::create(['id' => 3374, 'province_id' => 33, 'nama' => 'KOTA SEMARANG']);
        City::create(['id' => 3375, 'province_id' => 33, 'nama' => 'KOTA PEKALONGAN']);
        City::create(['id' => 3376, 'province_id' => 33, 'nama' => 'KOTA TEGAL']);
        City::create(['id' => 3401, 'province_id' => 34, 'nama' => 'KAB. KULON PROGO']);
        City::create(['id' => 3402, 'province_id' => 34, 'nama' => 'KAB. BANTUL']);
        City::create(['id' => 3403, 'province_id' => 34, 'nama' => 'KAB. GUNUNGKIDUL']);
        City::create(['id' => 3404, 'province_id' => 34, 'nama' => 'KAB. SLEMAN']);
        City::create(['id' => 3471, 'province_id' => 34, 'nama' => 'KOTA YOGYAKARTA']);
        City::create(['id' => 3501, 'province_id' => 35, 'nama' => 'KAB. PACITAN']);
        City::create(['id' => 3502, 'province_id' => 35, 'nama' => 'KAB. PONOROGO']);
        City::create(['id' => 3503, 'province_id' => 35, 'nama' => 'KAB. TRENGGALEK']);
        City::create(['id' => 3504, 'province_id' => 35, 'nama' => 'KAB. TULUNGAGUNG']);
        City::create(['id' => 3505, 'province_id' => 35, 'nama' => 'KAB. BLITAR']);
        City::create(['id' => 3506, 'province_id' => 35, 'nama' => 'KAB. KEDIRI']);
        City::create(['id' => 3507, 'province_id' => 35, 'nama' => 'KAB. MALANG']);
        City::create(['id' => 3508, 'province_id' => 35, 'nama' => 'KAB. LUMAJANG']);
        City::create(['id' => 3509, 'province_id' => 35, 'nama' => 'KAB. JEMBER']);
        City::create(['id' => 3510, 'province_id' => 35, 'nama' => 'KAB. BANYUWANGI']);
        City::create(['id' => 3511, 'province_id' => 35, 'nama' => 'KAB. BONDOWOSO']);
        City::create(['id' => 3512, 'province_id' => 35, 'nama' => 'KAB. SITUBONDO']);
        City::create(['id' => 3513, 'province_id' => 35, 'nama' => 'KAB. PROBOLINGGO']);
        City::create(['id' => 3514, 'province_id' => 35, 'nama' => 'KAB. PASURUAN']);
        City::create(['id' => 3515, 'province_id' => 35, 'nama' => 'KAB. SIDOARJO']);
        City::create(['id' => 3516, 'province_id' => 35, 'nama' => 'KAB. MOJOKERTO']);
        City::create(['id' => 3517, 'province_id' => 35, 'nama' => 'KAB. JOMBANG']);
        City::create(['id' => 3518, 'province_id' => 35, 'nama' => 'KAB. NGANJUK']);
        City::create(['id' => 3519, 'province_id' => 35, 'nama' => 'KAB. MADIUN']);
        City::create(['id' => 3520, 'province_id' => 35, 'nama' => 'KAB. MAGETAN']);
        City::create(['id' => 3521, 'province_id' => 35, 'nama' => 'KAB. NGAWI']);
        City::create(['id' => 3522, 'province_id' => 35, 'nama' => 'KAB. BOJONEGORO']);
        City::create(['id' => 3523, 'province_id' => 35, 'nama' => 'KAB. TUBAN']);
        City::create(['id' => 3524, 'province_id' => 35, 'nama' => 'KAB. LAMONGAN']);
        City::create(['id' => 3525, 'province_id' => 35, 'nama' => 'KAB. GRESIK']);
        City::create(['id' => 3526, 'province_id' => 35, 'nama' => 'KAB. BANGKALAN']);
        City::create(['id' => 3527, 'province_id' => 35, 'nama' => 'KAB. SAMPANG']);
        City::create(['id' => 3528, 'province_id' => 35, 'nama' => 'KAB. PAMEKASAN']);
        City::create(['id' => 3529, 'province_id' => 35, 'nama' => 'KAB. SUMENEP']);
        City::create(['id' => 3571, 'province_id' => 35, 'nama' => 'KOTA KEDIRI']);
        City::create(['id' => 3572, 'province_id' => 35, 'nama' => 'KOTA BLITAR']);
        City::create(['id' => 3573, 'province_id' => 35, 'nama' => 'KOTA MALANG']);
        City::create(['id' => 3574, 'province_id' => 35, 'nama' => 'KOTA PROBOLINGGO']);
        City::create(['id' => 3575, 'province_id' => 35, 'nama' => 'KOTA PASURUAN']);
        City::create(['id' => 3576, 'province_id' => 35, 'nama' => 'KOTA MOJOKERTO']);
        City::create(['id' => 3577, 'province_id' => 35, 'nama' => 'KOTA MADIUN']);
        City::create(['id' => 3578, 'province_id' => 35, 'nama' => 'KOTA SURABAYA']);
        City::create(['id' => 3579, 'province_id' => 35, 'nama' => 'KOTA BATU']);
        City::create(['id' => 3601, 'province_id' => 36, 'nama' => 'KAB. PANDEGLANG']);
        City::create(['id' => 3602, 'province_id' => 36, 'nama' => 'KAB. LEBAK']);
        City::create(['id' => 3603, 'province_id' => 36, 'nama' => 'KAB. TANGERANG']);
        City::create(['id' => 3604, 'province_id' => 36, 'nama' => 'KAB. SERANG']);
        City::create(['id' => 3671, 'province_id' => 36, 'nama' => 'KOTA TANGERANG']);
        City::create(['id' => 3672, 'province_id' => 36, 'nama' => 'KOTA CILEGON']);
        City::create(['id' => 3673, 'province_id' => 36, 'nama' => 'KOTA SERANG']);
        City::create(['id' => 3674, 'province_id' => 36, 'nama' => 'KOTA TANGERANG SELATAN']);
        City::create(['id' => 5101, 'province_id' => 51, 'nama' => 'KAB. JEMBRANA']);
        City::create(['id' => 5102, 'province_id' => 51, 'nama' => 'KAB. TABANAN']);
        City::create(['id' => 5103, 'province_id' => 51, 'nama' => 'KAB. BADUNG']);
        City::create(['id' => 5104, 'province_id' => 51, 'nama' => 'KAB. GIANYAR']);
        City::create(['id' => 5105, 'province_id' => 51, 'nama' => 'KAB. KLUNGKUNG']);
        City::create(['id' => 5106, 'province_id' => 51, 'nama' => 'KAB. BANGLI']);
        City::create(['id' => 5107, 'province_id' => 51, 'nama' => 'KAB. KARANGASEM']);
        City::create(['id' => 5108, 'province_id' => 51, 'nama' => 'KAB. BULELENG']);
        City::create(['id' => 5171, 'province_id' => 51, 'nama' => 'KOTA DENPASAR']);
        City::create(['id' => 5201, 'province_id' => 52, 'nama' => 'KAB. LOMBOK BARAT']);
        City::create(['id' => 5202, 'province_id' => 52, 'nama' => 'KAB. LOMBOK TENGAH']);
        City::create(['id' => 5203, 'province_id' => 52, 'nama' => 'KAB. LOMBOK TIMUR']);
        City::create(['id' => 5204, 'province_id' => 52, 'nama' => 'KAB. SUMBAWA']);
        City::create(['id' => 5205, 'province_id' => 52, 'nama' => 'KAB. DOMPU']);
        City::create(['id' => 5206, 'province_id' => 52, 'nama' => 'KAB. BIMA']);
        City::create(['id' => 5207, 'province_id' => 52, 'nama' => 'KAB. SUMBAWA BARAT']);
        City::create(['id' => 5208, 'province_id' => 52, 'nama' => 'KAB. LOMBOK UTARA']);
        City::create(['id' => 5271, 'province_id' => 52, 'nama' => 'KOTA MATARAM']);
        City::create(['id' => 5272, 'province_id' => 52, 'nama' => 'KOTA BIMA']);
        City::create(['id' => 5301, 'province_id' => 53, 'nama' => 'KAB. KUPANG']);
        City::create(['id' => 5302, 'province_id' => 53, 'nama' => 'KAB TIMOR TENGAH SELATAN']);
        City::create(['id' => 5303, 'province_id' => 53, 'nama' => 'KAB. TIMOR TENGAH UTARA']);
        City::create(['id' => 5304, 'province_id' => 53, 'nama' => 'KAB. BELU']);
        City::create(['id' => 5305, 'province_id' => 53, 'nama' => 'KAB. ALOR']);
        City::create(['id' => 5306, 'province_id' => 53, 'nama' => 'KAB. FLORES TIMUR']);
        City::create(['id' => 5307, 'province_id' => 53, 'nama' => 'KAB. SIKKA']);
        City::create(['id' => 5308, 'province_id' => 53, 'nama' => 'KAB. ENDE']);
        City::create(['id' => 5309, 'province_id' => 53, 'nama' => 'KAB. NGADA']);
        City::create(['id' => 5310, 'province_id' => 53, 'nama' => 'KAB. MANGGARAI']);
        City::create(['id' => 5311, 'province_id' => 53, 'nama' => 'KAB. SUMBA TIMUR']);
        City::create(['id' => 5312, 'province_id' => 53, 'nama' => 'KAB. SUMBA BARAT']);
        City::create(['id' => 5313, 'province_id' => 53, 'nama' => 'KAB. LEMBATA']);
        City::create(['id' => 5314, 'province_id' => 53, 'nama' => 'KAB. ROTE NDAO']);
        City::create(['id' => 5315, 'province_id' => 53, 'nama' => 'KAB. MANGGARAI BARAT']);
        City::create(['id' => 5316, 'province_id' => 53, 'nama' => 'KAB. NAGEKEO']);
        City::create(['id' => 5317, 'province_id' => 53, 'nama' => 'KAB. SUMBA TENGAH']);
        City::create(['id' => 5318, 'province_id' => 53, 'nama' => 'KAB. SUMBA BARAT DAYA']);
        City::create(['id' => 5319, 'province_id' => 53, 'nama' => 'KAB. MANGGARAI TIMUR']);
        City::create(['id' => 5320, 'province_id' => 53, 'nama' => 'KAB. SABU RAIJUA']);
        City::create(['id' => 5321, 'province_id' => 53, 'nama' => 'KAB. MALAKA']);
        City::create(['id' => 5371, 'province_id' => 53, 'nama' => 'KOTA KUPANG']);
        City::create(['id' => 6101, 'province_id' => 61, 'nama' => 'KAB. SAMBAS']);
        City::create(['id' => 6102, 'province_id' => 61, 'nama' => 'KAB. MEMPAWAH']);
        City::create(['id' => 6103, 'province_id' => 61, 'nama' => 'KAB. SANGGAU']);
        City::create(['id' => 6104, 'province_id' => 61, 'nama' => 'KAB. KETAPANG']);
        City::create(['id' => 6105, 'province_id' => 61, 'nama' => 'KAB. SINTANG']);
        City::create(['id' => 6106, 'province_id' => 61, 'nama' => 'KAB. KAPUAS HULU']);
        City::create(['id' => 6107, 'province_id' => 61, 'nama' => 'KAB. BENGKAYANG']);
        City::create(['id' => 6108, 'province_id' => 61, 'nama' => 'KAB. LANDAK']);
        City::create(['id' => 6109, 'province_id' => 61, 'nama' => 'KAB. SEKADAU']);
        City::create(['id' => 6110, 'province_id' => 61, 'nama' => 'KAB. MELAWI']);
        City::create(['id' => 6111, 'province_id' => 61, 'nama' => 'KAB. KAYONG UTARA']);
        City::create(['id' => 6112, 'province_id' => 61, 'nama' => 'KAB. KUBU RAYA']);
        City::create(['id' => 6171, 'province_id' => 61, 'nama' => 'KOTA PONTIANAK']);
        City::create(['id' => 6172, 'province_id' => 61, 'nama' => 'KOTA SINGKAWANG']);
        City::create(['id' => 6201, 'province_id' => 62, 'nama' => 'KAB. KOTAWARINGIN BARAT']);
        City::create(['id' => 6202, 'province_id' => 62, 'nama' => 'KAB. KOTAWARINGIN TIMUR']);
        City::create(['id' => 6203, 'province_id' => 62, 'nama' => 'KAB. KAPUAS']);
        City::create(['id' => 6204, 'province_id' => 62, 'nama' => 'KAB. BARITO SELATAN']);
        City::create(['id' => 6205, 'province_id' => 62, 'nama' => 'KAB. BARITO UTARA']);
        City::create(['id' => 6206, 'province_id' => 62, 'nama' => 'KAB. KATINGAN']);
        City::create(['id' => 6207, 'province_id' => 62, 'nama' => 'KAB. SERUYAN']);
        City::create(['id' => 6208, 'province_id' => 62, 'nama' => 'KAB. SUKAMARA']);
        City::create(['id' => 6209, 'province_id' => 62, 'nama' => 'KAB. LAMANDAU']);
        City::create(['id' => 6210, 'province_id' => 62, 'nama' => 'KAB. GUNUNG MAS']);
        City::create(['id' => 6211, 'province_id' => 62, 'nama' => 'KAB. PULANG PISAU']);
        City::create(['id' => 6212, 'province_id' => 62, 'nama' => 'KAB. MURUNG RAYA']);
        City::create(['id' => 6213, 'province_id' => 62, 'nama' => 'KAB. BARITO TIMUR']);
        City::create(['id' => 6271, 'province_id' => 62, 'nama' => 'KOTA PALANGKARAYA']);
        City::create(['id' => 6301, 'province_id' => 63, 'nama' => 'KAB. TANAH LAUT']);
        City::create(['id' => 6302, 'province_id' => 63, 'nama' => 'KAB. KOTABARU']);
        City::create(['id' => 6303, 'province_id' => 63, 'nama' => 'KAB. BANJAR']);
        City::create(['id' => 6304, 'province_id' => 63, 'nama' => 'KAB. BARITO KUALA']);
        City::create(['id' => 6305, 'province_id' => 63, 'nama' => 'KAB. TAPIN']);
        City::create(['id' => 6306, 'province_id' => 63, 'nama' => 'KAB. HULU SUNGAI SELATAN']);
        City::create(['id' => 6307, 'province_id' => 63, 'nama' => 'KAB. HULU SUNGAI TENGAH']);
        City::create(['id' => 6308, 'province_id' => 63, 'nama' => 'KAB. HULU SUNGAI UTARA']);
        City::create(['id' => 6309, 'province_id' => 63, 'nama' => 'KAB. TABALONG']);
        City::create(['id' => 6310, 'province_id' => 63, 'nama' => 'KAB. TANAH BUMBU']);
        City::create(['id' => 6311, 'province_id' => 63, 'nama' => 'KAB. BALANGAN']);
        City::create(['id' => 6371, 'province_id' => 63, 'nama' => 'KOTA BANJARMASIN']);
        City::create(['id' => 6372, 'province_id' => 63, 'nama' => 'KOTA BANJARBARU']);
        City::create(['id' => 6401, 'province_id' => 64, 'nama' => 'KAB. PASER']);
        City::create(['id' => 6402, 'province_id' => 64, 'nama' => 'KAB. KUTAI KARTANEGARA']);
        City::create(['id' => 6403, 'province_id' => 64, 'nama' => 'KAB. BERAU']);
        City::create(['id' => 6407, 'province_id' => 64, 'nama' => 'KAB. KUTAI BARAT']);
        City::create(['id' => 6408, 'province_id' => 64, 'nama' => 'KAB. KUTAI TIMUR']);
        City::create(['id' => 6409, 'province_id' => 64, 'nama' => 'KAB. PENAJAM PASER UTARA']);
        City::create(['id' => 6411, 'province_id' => 64, 'nama' => 'KAB. MAHAKAM ULU']);
        City::create(['id' => 6471, 'province_id' => 64, 'nama' => 'KOTA BALIKPAPAN']);
        City::create(['id' => 6472, 'province_id' => 64, 'nama' => 'KOTA SAMARINDA']);
        City::create(['id' => 6474, 'province_id' => 64, 'nama' => 'KOTA BONTANG']);
        City::create(['id' => 6501, 'province_id' => 65, 'nama' => 'KAB. BULUNGAN']);
        City::create(['id' => 6502, 'province_id' => 65, 'nama' => 'KAB. MALINAU']);
        City::create(['id' => 6503, 'province_id' => 65, 'nama' => 'KAB. NUNUKAN']);
        City::create(['id' => 6504, 'province_id' => 65, 'nama' => 'KAB. TANA TIDUNG']);
        City::create(['id' => 6571, 'province_id' => 65, 'nama' => 'KOTA TARAKAN']);
        City::create(['id' => 7101, 'province_id' => 71, 'nama' => 'KAB. BOLAANG MONGONDOW']);
        City::create(['id' => 7102, 'province_id' => 71, 'nama' => 'KAB. MINAHASA']);
        City::create(['id' => 7103, 'province_id' => 71, 'nama' => 'KAB. KEPULAUAN SANGIHE']);
        City::create(['id' => 7104, 'province_id' => 71, 'nama' => 'KAB. KEPULAUAN TALAUD']);
        City::create(['id' => 7105, 'province_id' => 71, 'nama' => 'KAB. MINAHASA SELATAN']);
        City::create(['id' => 7106, 'province_id' => 71, 'nama' => 'KAB. MINAHASA UTARA']);
        City::create(['id' => 7107, 'province_id' => 71, 'nama' => 'KAB. MINAHASA TENGGARA']);
        City::create(['id' => 7108, 'province_id' => 71, 'nama' => 'KAB. BOLAANG MONGONDOW UTARA']);
        City::create(['id' => 7109, 'province_id' => 71, 'nama' => 'KAB. KEP. SIAU TAGULANDANG BIARO']);
        City::create(['id' => 7110, 'province_id' => 71, 'nama' => 'KAB. BOLAANG MONGONDOW TIMUR']);
        City::create(['id' => 7111, 'province_id' => 71, 'nama' => 'KAB. BOLAANG MONGONDOW SELATAN']);
        City::create(['id' => 7171, 'province_id' => 71, 'nama' => 'KOTA MANADO']);
        City::create(['id' => 7172, 'province_id' => 71, 'nama' => 'KOTA BITUNG']);
        City::create(['id' => 7173, 'province_id' => 71, 'nama' => 'KOTA TOMOHON']);
        City::create(['id' => 7174, 'province_id' => 71, 'nama' => 'KOTA KOTAMOBAGU']);
        City::create(['id' => 7201, 'province_id' => 72, 'nama' => 'KAB. BANGGAI']);
        City::create(['id' => 7202, 'province_id' => 72, 'nama' => 'KAB. POSO']);
        City::create(['id' => 7203, 'province_id' => 72, 'nama' => 'KAB. DONGGALA']);
        City::create(['id' => 7204, 'province_id' => 72, 'nama' => 'KAB. TOLI TOLI']);
        City::create(['id' => 7205, 'province_id' => 72, 'nama' => 'KAB. BUOL']);
        City::create(['id' => 7206, 'province_id' => 72, 'nama' => 'KAB. MOROWALI']);
        City::create(['id' => 7207, 'province_id' => 72, 'nama' => 'KAB. BANGGAI KEPULAUAN']);
        City::create(['id' => 7208, 'province_id' => 72, 'nama' => 'KAB. PARIGI MOUTONG']);
        City::create(['id' => 7209, 'province_id' => 72, 'nama' => 'KAB. TOJO UNA UNA']);
        City::create(['id' => 7210, 'province_id' => 72, 'nama' => 'KAB. SIGI']);
        City::create(['id' => 7211, 'province_id' => 72, 'nama' => 'KAB. BANGGAI LAUT']);
        City::create(['id' => 7212, 'province_id' => 72, 'nama' => 'KAB. MOROWALI UTARA']);
        City::create(['id' => 7271, 'province_id' => 72, 'nama' => 'KOTA PALU']);
        City::create(['id' => 7301, 'province_id' => 73, 'nama' => 'KAB. KEPULAUAN SELAYAR']);
        City::create(['id' => 7302, 'province_id' => 73, 'nama' => 'KAB. BULUKUMBA']);
        City::create(['id' => 7303, 'province_id' => 73, 'nama' => 'KAB. BANTAENG']);
        City::create(['id' => 7304, 'province_id' => 73, 'nama' => 'KAB. JENEPONTO']);
        City::create(['id' => 7305, 'province_id' => 73, 'nama' => 'KAB. TAKALAR']);
        City::create(['id' => 7306, 'province_id' => 73, 'nama' => 'KAB. GOWA']);
        City::create(['id' => 7307, 'province_id' => 73, 'nama' => 'KAB. SINJAI']);
        City::create(['id' => 7308, 'province_id' => 73, 'nama' => 'KAB. BONE']);
        City::create(['id' => 7309, 'province_id' => 73, 'nama' => 'KAB. MAROS']);
        City::create(['id' => 7310, 'province_id' => 73, 'nama' => 'KAB. PANGKAJENE KEPULAUAN']);
        City::create(['id' => 7311, 'province_id' => 73, 'nama' => 'KAB. BARRU']);
        City::create(['id' => 7312, 'province_id' => 73, 'nama' => 'KAB. SOPPENG']);
        City::create(['id' => 7313, 'province_id' => 73, 'nama' => 'KAB. WAJO']);
        City::create(['id' => 7314, 'province_id' => 73, 'nama' => 'KAB. SIDENRENG RAPPANG']);
        City::create(['id' => 7315, 'province_id' => 73, 'nama' => 'KAB. PINRANG']);
        City::create(['id' => 7316, 'province_id' => 73, 'nama' => 'KAB. ENREKANG']);
        City::create(['id' => 7317, 'province_id' => 73, 'nama' => 'KAB. LUWU']);
        City::create(['id' => 7318, 'province_id' => 73, 'nama' => 'KAB. TANA TORAJA']);
        City::create(['id' => 7322, 'province_id' => 73, 'nama' => 'KAB. LUWU UTARA']);
        City::create(['id' => 7324, 'province_id' => 73, 'nama' => 'KAB. LUWU TIMUR']);
        City::create(['id' => 7326, 'province_id' => 73, 'nama' => 'KAB. TORAJA UTARA']);
        City::create(['id' => 7371, 'province_id' => 73, 'nama' => 'KOTA MAKASSAR']);
        City::create(['id' => 7372, 'province_id' => 73, 'nama' => 'KOTA PARE PARE']);
        City::create(['id' => 7373, 'province_id' => 73, 'nama' => 'KOTA PALOPO']);
        City::create(['id' => 7401, 'province_id' => 74, 'nama' => 'KAB. KOLAKA']);
        City::create(['id' => 7402, 'province_id' => 74, 'nama' => 'KAB. KONAWE']);
        City::create(['id' => 7403, 'province_id' => 74, 'nama' => 'KAB. MUNA']);
        City::create(['id' => 7404, 'province_id' => 74, 'nama' => 'KAB. BUTON']);
        City::create(['id' => 7405, 'province_id' => 74, 'nama' => 'KAB. KONAWE SELATAN']);
        City::create(['id' => 7406, 'province_id' => 74, 'nama' => 'KAB. BOMBANA']);
        City::create(['id' => 7407, 'province_id' => 74, 'nama' => 'KAB. WAKATOBI']);
        City::create(['id' => 7408, 'province_id' => 74, 'nama' => 'KAB. KOLAKA UTARA']);
        City::create(['id' => 7409, 'province_id' => 74, 'nama' => 'KAB. KONAWE UTARA']);
        City::create(['id' => 7410, 'province_id' => 74, 'nama' => 'KAB. BUTON UTARA']);
        City::create(['id' => 7411, 'province_id' => 74, 'nama' => 'KAB. KOLAKA TIMUR']);
        City::create(['id' => 7412, 'province_id' => 74, 'nama' => 'KAB. KONAWE KEPULAUAN']);
        City::create(['id' => 7413, 'province_id' => 74, 'nama' => 'KAB. MUNA BARAT']);
        City::create(['id' => 7414, 'province_id' => 74, 'nama' => 'KAB. BUTON TENGAH']);
        City::create(['id' => 7415, 'province_id' => 74, 'nama' => 'KAB. BUTON SELATAN']);
        City::create(['id' => 7471, 'province_id' => 74, 'nama' => 'KOTA KENDARI']);
        City::create(['id' => 7472, 'province_id' => 74, 'nama' => 'KOTA BAU BAU']);
        City::create(['id' => 7501, 'province_id' => 75, 'nama' => 'KAB. GORONTALO']);
        City::create(['id' => 7502, 'province_id' => 75, 'nama' => 'KAB. BOALEMO']);
        City::create(['id' => 7503, 'province_id' => 75, 'nama' => 'KAB. BONE BOLANGO']);
        City::create(['id' => 7504, 'province_id' => 75, 'nama' => 'KAB. PAHUWATO']);
        City::create(['id' => 7505, 'province_id' => 75, 'nama' => 'KAB. GORONTALO UTARA']);
        City::create(['id' => 7571, 'province_id' => 75, 'nama' => 'KOTA GORONTALO']);
        City::create(['id' => 7601, 'province_id' => 76, 'nama' => 'KAB. MAMUJU UTARA']);
        City::create(['id' => 7602, 'province_id' => 76, 'nama' => 'KAB. MAMUJU']);
        City::create(['id' => 7603, 'province_id' => 76, 'nama' => 'KAB. MAMASA']);
        City::create(['id' => 7604, 'province_id' => 76, 'nama' => 'KAB. POLEWALI MANDAR']);
        City::create(['id' => 7605, 'province_id' => 76, 'nama' => 'KAB. MAJENE']);
        City::create(['id' => 7606, 'province_id' => 76, 'nama' => 'KAB. MAMUJU TENGAH']);
        City::create(['id' => 8101, 'province_id' => 81, 'nama' => 'KAB. MALUKU TENGAH']);
        City::create(['id' => 8102, 'province_id' => 81, 'nama' => 'KAB. MALUKU TENGGARA']);
        City::create(['id' => 8103, 'province_id' => 81, 'nama' => 'KAB. MALUKU TENGGARA BARAT']);
        City::create(['id' => 8104, 'province_id' => 81, 'nama' => 'KAB. BURU']);
        City::create(['id' => 8105, 'province_id' => 81, 'nama' => 'KAB. SERAM BAGIAN TIMUR']);
        City::create(['id' => 8106, 'province_id' => 81, 'nama' => 'KAB. SERAM BAGIAN BARAT']);
        City::create(['id' => 8107, 'province_id' => 81, 'nama' => 'KAB. KEPULAUAN ARU']);
        City::create(['id' => 8108, 'province_id' => 81, 'nama' => 'KAB. MALUKU BARAT DAYA']);
        City::create(['id' => 8109, 'province_id' => 81, 'nama' => 'KAB. BURU SELATAN']);
        City::create(['id' => 8171, 'province_id' => 81, 'nama' => 'KOTA AMBON']);
        City::create(['id' => 8172, 'province_id' => 81, 'nama' => 'KOTA TUAL']);
        City::create(['id' => 8201, 'province_id' => 82, 'nama' => 'KAB. HALMAHERA BARAT']);
        City::create(['id' => 8202, 'province_id' => 82, 'nama' => 'KAB. HALMAHERA TENGAH']);
        City::create(['id' => 8203, 'province_id' => 82, 'nama' => 'KAB. HALMAHERA UTARA']);
        City::create(['id' => 8204, 'province_id' => 82, 'nama' => 'KAB. HALMAHERA SELATAN']);
        City::create(['id' => 8205, 'province_id' => 82, 'nama' => 'KAB. KEPULAUAN SULA']);
        City::create(['id' => 8206, 'province_id' => 82, 'nama' => 'KAB. HALMAHERA TIMUR']);
        City::create(['id' => 8207, 'province_id' => 82, 'nama' => 'KAB. PULAU MOROTAI']);
        City::create(['id' => 8208, 'province_id' => 82, 'nama' => 'KAB. PULAU TALIABU']);
        City::create(['id' => 8271, 'province_id' => 82, 'nama' => 'KOTA TERNATE']);
        City::create(['id' => 8272, 'province_id' => 82, 'nama' => 'KOTA TIDORE KEPULAUAN']);
        City::create(['id' => 9101, 'province_id' => 91, 'nama' => 'KAB. MERAUKE']);
        City::create(['id' => 9102, 'province_id' => 91, 'nama' => 'KAB. JAYAWIJAYA']);
        City::create(['id' => 9103, 'province_id' => 91, 'nama' => 'KAB. JAYAPURA']);
        City::create(['id' => 9104, 'province_id' => 91, 'nama' => 'KAB. NABIRE']);
        City::create(['id' => 9105, 'province_id' => 91, 'nama' => 'KAB. KEPULAUAN YAPEN']);
        City::create(['id' => 9106, 'province_id' => 91, 'nama' => 'KAB. BIAK NUMFOR']);
        City::create(['id' => 9107, 'province_id' => 91, 'nama' => 'KAB. PUNCAK JAYA']);
        City::create(['id' => 9108, 'province_id' => 91, 'nama' => 'KAB. PANIAI']);
        City::create(['id' => 9109, 'province_id' => 91, 'nama' => 'KAB. MIMIKA']);
        City::create(['id' => 9110, 'province_id' => 91, 'nama' => 'KAB. SARMI']);
        City::create(['id' => 9111, 'province_id' => 91, 'nama' => 'KAB. KEEROM']);
        City::create(['id' => 9112, 'province_id' => 91, 'nama' => 'KAB. PEGUNUNGAN BINTANG']);
        City::create(['id' => 9113, 'province_id' => 91, 'nama' => 'KAB. YAHUKIMO']);
        City::create(['id' => 9114, 'province_id' => 91, 'nama' => 'KAB. TOLIKARA']);
        City::create(['id' => 9115, 'province_id' => 91, 'nama' => 'KAB. WAROPEN']);
        City::create(['id' => 9116, 'province_id' => 91, 'nama' => 'KAB. BOVEN DIGOEL']);
        City::create(['id' => 9117, 'province_id' => 91, 'nama' => 'KAB. MAPPI']);
        City::create(['id' => 9118, 'province_id' => 91, 'nama' => 'KAB. ASMAT']);
        City::create(['id' => 9119, 'province_id' => 91, 'nama' => 'KAB. SUPIORI']);
        City::create(['id' => 9120, 'province_id' => 91, 'nama' => 'KAB. MAMBERAMO RAYA']);
        City::create(['id' => 9121, 'province_id' => 91, 'nama' => 'KAB. MAMBERAMO TENGAH']);
        City::create(['id' => 9122, 'province_id' => 91, 'nama' => 'KAB. YALIMO']);
        City::create(['id' => 9123, 'province_id' => 91, 'nama' => 'KAB. LANNY JAYA']);
        City::create(['id' => 9124, 'province_id' => 91, 'nama' => 'KAB. NDUGA']);
        City::create(['id' => 9125, 'province_id' => 91, 'nama' => 'KAB. PUNCAK']);
        City::create(['id' => 9126, 'province_id' => 91, 'nama' => 'KAB. DOGIYAI']);
        City::create(['id' => 9127, 'province_id' => 91, 'nama' => 'KAB. INTAN JAYA']);
        City::create(['id' => 9128, 'province_id' => 91, 'nama' => 'KAB. DEIYAI']);
        City::create(['id' => 9171, 'province_id' => 91, 'nama' => 'KOTA JAYAPURA']);
        City::create(['id' => 9201, 'province_id' => 92, 'nama' => 'KAB. SORONG']);
        City::create(['id' => 9202, 'province_id' => 92, 'nama' => 'KAB. MANOKWARI']);
        City::create(['id' => 9203, 'province_id' => 92, 'nama' => 'KAB. FAK FAK']);
        City::create(['id' => 9204, 'province_id' => 92, 'nama' => 'KAB. SORONG SELATAN']);
        City::create(['id' => 9205, 'province_id' => 92, 'nama' => 'KAB. RAJA AMPAT']);
        City::create(['id' => 9206, 'province_id' => 92, 'nama' => 'KAB. TELUK BINTUNI']);
        City::create(['id' => 9207, 'province_id' => 92, 'nama' => 'KAB. TELUK WONDAMA']);
        City::create(['id' => 9208, 'province_id' => 92, 'nama' => 'KAB. KAIMANA']);
        City::create(['id' => 9209, 'province_id' => 92, 'nama' => 'KAB. TAMBRAUW']);
        City::create(['id' => 9210, 'province_id' => 92, 'nama' => 'KAB. MAYBRAT']);
        City::create(['id' => 9211, 'province_id' => 92, 'nama' => 'KAB. MANOKWARI SELATAN']);
        City::create(['id' => 9212, 'province_id' => 92, 'nama' => 'KAB. PEGUNUNGAN ARFAK']);
        City::create(['id' => 9271, 'province_id' => 92, 'nama' => 'KOTA SORONG']);
    }
}
