version: '3.7'

services:
  app:
    container_name: bumdest-app
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - 8080:80
    environment:
      - APP_NAME=Bumdest
      - APP_ENV=production
      - APP_KEY=base64:AiowrBTOa18nb9vXvfUF5DG/uDbJjUPd8yoo9NxhLiE=
      - APP_DEBUG=false
      - APP_URL=https://bumdest.gals.my.id
      - ASSET_URL=https://bumdest.gals.my.id
      - DB_CONNECTION=mysql
      - DB_HOST=bumdest-db
      - DB_PORT=3306
      - DB_DATABASE=bumdest
      - DB_USERNAME=root
      - DB_PASSWORD=root
      - IDC_SPACES_KEY=ZJ343T6L8MLHJU96VUPW
      - IDC_SPACES_SECRET=Dihzl2JJiOy8K6iXWzCzFeJtvWRUjvWqwoBkrIIq
      - IDC_SPACES_ENDPOINT=https://is3.cloudhost.id/
      - IDC_SPACES_REGION=is3
      - IDC_SPACES_BUCKET=bumdest
  db:
    image: mysql:8.0
    container_name: bumdest-db
    restart: unless-stopped
    cap_add:
      - SYS_NICE
    environment:
      - MYSQL_DATABASE=bumdest
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - '3306:3306'
    volumes:
      - /var/lib/mysql:/var/lib/mysql